/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Popcorn, PopcornInterface } from "../Popcorn";

const _abi = [
  {
    inputs: [],
    name: "var1",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405260008055348015601357600080fd5b50607d806100226000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806367e919b614602d575b600080fd5b603560005481565b60405190815260200160405180910390f3fea26469706673582212204add2ffb65c25d0014690b02e61a89f0fcd55391b1b66e91765c14d63e055f5e64736f6c63430008100033";

type PopcornConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PopcornConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Popcorn__factory extends ContractFactory {
  constructor(...args: PopcornConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Popcorn> {
    return super.deploy(overrides || {}) as Promise<Popcorn>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Popcorn {
    return super.attach(address) as Popcorn;
  }
  override connect(signer: Signer): Popcorn__factory {
    return super.connect(signer) as Popcorn__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PopcornInterface {
    return new utils.Interface(_abi) as PopcornInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Popcorn {
    return new Contract(address, _abi, signerOrProvider) as Popcorn;
  }
}
